server:
  port: 10003
spring:
  rabbitmq:
    host: 192.168.10.151
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      refresh:
        enabled: true

config:
  picServerUrl: http://36.152.34.20:100  #外网地址
  uploadUrl: http://192.168.10.201:18089 #内网地址
  tmpFilePath: /program/tmp
