server:
  port: 10002
spring:
  rabbitmq:
    host: 192.168.10.151
    port: 5672
    username: admin
    password: admin
config:
  picServerUrl: http://36.152.34.20:500  #外网地址
  uploadUrl: http://192.168.10.201:18089 #内网地址
  tmpFilePath: /program/tmp
management:
  endpoints:
    web:
      exposure:
        include:  bus-refresh
