eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10000/eureka/
redis:
  cache:
    clusterNodes: 192.168.10.201:7000,192.168.10.201:7001,192.168.10.201:7002,192.168.10.201:7003
    #commandTimeout: 10000
    #expireSeconds: 120
    maxTotal: 100
    maxIdle: 10
    minIdle: 0
    #testOnBorrow: true
    #testOnReturn: true
    #maxWaitMillis: 60000
    #timeBetweenEvictionRunsMillis: 30000
    #testWhileIdle: true
    #numTestsPerEvictionRun: 3
    #minEvictableIdleTimeMillis: 60000
ecms:
  login: /ecms/login #登陆界面
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages/messages
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        default-property-inclusion: always
        time-zone: GMT+8
    
pay: 
  ali:
    appId: 2016082700320595
    notifyUrl: 180.109.80.193:10003/
    returnUrl: 180.109.80.193:10003/
    url: https://openapi.alipaydev.com/gateway.do
    charset: UTF-8
    format: json
    aliPayPublicKey: classpath:pay/ali/pub.txt
    rsaPrivateKey: classpath:pay/ali/pri.txt
    logPath: D:/program/test/log/pay/alipay.log
    singType: RSA2 
    payBackUrl: order/orderPayCallback
utils:
  smsAccount: N1212062
  smsPassword: gNOqJ3159H76cb
  smsUrl: http://smssh1.253.com/msg/send/json
  uploadUrl: http://192.168.10.201:18089
  tmpFilePath: /program/tmp  
  
