server:
  port: 10002
spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis: 300000
        time-between-eviction-runs-millis: 0
        validation-query: select 1 FROM DUAL
        validation-query-timeout: 60000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat
        share-prepared-statements: true
      datasource:
        master: #主库 读写
          username: tea_trade
          password: teatrade_nlx
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@192.168.10.205:1521:orcl
        slave: #从库 写
          username: tea_trade
          password: teatrade_nlx
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@192.168.10.205:1521:orcl
#分页插件配置
pagehelper: 
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  
#swagger地址配置   
swagger:
  host: localhost:${server.port}
mybatis:
  mapper-locations: classpath*:mapper/*.xml  
logging:
  config: classpath:log4j2.xml
config:
  picServerUrl: http://36.152.34.20:18080  #外网地址
  uploadUrl: http://192.168.10.201:18089 #内网地址
  tmpFilePath: /program/tmp
